import { Router } from "express";
import { authRoute } from "./auth";
import { productRoutes } from "./products";
import { checkAuth } from "../middlewares/auth";
import { storeRoutes } from "./store";
import { categoryRoutes } from "./categories";
import { orderRoutes } from "./orders";
import { rootErrorHandler } from "../root-error-handler";
import { paymentRoutes } from "./payment";
import { adminRoleCheck, sellerRoleCheck } from "../middlewares/roles";
import { adminRoute } from "./admin";
import { userRoutes } from "./user";
import { cacheSuccess } from "../middlewares/cache";
import apicache from "apicache";
import { getProfit } from "../middlewares";
const router = Router();
router.use("/auth", authRoute);
router.use("/user", checkAuth, cacheSuccess, userRoutes);
router.use("/stores", cacheSuccess, storeRoutes);
router.use("/products", productRoutes);
router.use("/categories", cacheSuccess, categoryRoutes);
router.use("/orders", checkAuth, cacheSuccess, orderRoutes);
router.use("/payment", checkAuth, paymentRoutes);
router.use("/admin", checkAuth, adminRoleCheck, adminRoute);
router.get("/cache", (req, res) => {
  res.json(apicache.getIndex());
});
router.get("/clear", (req, res) => {
  res.json(apicache.clear(""));
});
export default router;
