import { Router } from "express";
import { authRoute } from "./auth";
import { productRoutes } from "./products";
import { checkAuth } from "../middlewares/auth";
import { storeRoutes } from "./store";
import { categoryRoutes } from "./categories";
import { cartRoutes } from "./cart";
import { orderRoutes } from "./orders";
import { rootErrorHandler } from "../root-error-handler";
import { paymentRoutes } from "./payment";
import { sellerRoleCheck } from "../middlewares/roles";
import { adminRoute } from "./admin";
import { userRoutes } from "./user";
const router = Router();
router.use("/auth", authRoute);
router.use("/user", checkAuth, userRoutes);
router.use("/stores", checkAuth, storeRoutes);
router.use("/products", checkAuth, productRoutes);
router.use("/categories", categoryRoutes);
router.use("/cart", checkAuth, cartRoutes);
router.use("/orders", checkAuth, orderRoutes);
router.use("/payment", checkAuth, paymentRoutes);
router.use("/admin", checkAuth, sellerRoleCheck, adminRoute);

export default router;
